### ISSUE TITLE
Update existing layers

### ISSUE THREAD

**Issue by StephMills** [UGS-GIO/Minerals-Metals#11]
- Can we use the AGRC cadastre land ownership layer, instead of only BLM and USFS? It will still have BLM and USFS, but also SITLA etc, and will have up to date info on WSA and WAs. The WSA Mineral Land Assessment layer is out of date, I would recommend removing it and just having the single land ownership layer

- Is it possible to change the background to the gray hillshade? 

- Can we please change the "Mining Districts" layer title in the legend to "Metalliferous Mining Districts"?

- I think with all the other solid polygons on the map (eg land ownership, IM potential) it may be better for the mining districts to just be outlines - thoughts? I'm not sure how that would look with all the other changes, open to suggestions.

- I've updated the Mining Districts layer to include a TYPE field that they can be colored by. Located: M:\Shared drives\UGS_Energy Mineral\Webmap_MinResc

**Comment by marshallrobinson** [comment]
Thanks for the comments! I think what you have mentioned is all doable and sounds good. I'll check with @jjhi11 to see how much time he thinks it would take to do them.

**Comment by jjhi11** [comment]
@StephMills pretty sure we can do all of these within a day or two of work

**Comment by jjhi11** [comment]
anyone know where the sitla ownership layer is?  the one on our portal is a table. i thought i used it in the app previously but cant find it.

**Comment by StephMills** [comment]
Hi jay, following on from our chat:

BLM, Bur Reclaim - yellow
SITLA (state trust lands) - blue
Natl Rec, Parks, Monument - medium green
Natl forest, wilderness, wildlife - light green
Military, other fed - gray
State parks, wildlife - dark green
State sov lands, other state - blue gray
Tribal lands - orange

@arupke what are the Bankhead-Jones lands? I've never been sure what those are. do they fit into one of the categories above?

**Comment by jjhi11** [comment]
Thanks Stephanie

**Comment by arupke** [comment]
Unless there is a reason not to, I think we should follow the standard coloration scheme for property that SITLA has put forward. It mostly lines up with the colors you show above, but there are a few differences. You can view their color scheme here:

https://platmap.trustlands.utah.gov/

Bankhead Jones is a weird designation of BLM land. We can just show it as BLM land for our purposes.

**Comment by StephMills** [comment]
My thinking was that their color scheme is overly complex for our purposes. Maybe we can include a link to their webmap for people who really want to delve into land ownership? I'm leaning towards our map would be more effective if we reduced the number of categories and labelled them more intuitively (case in point, even I didn't know what Bankhead Jones lands were). Would this create any issue with the existing BLM requirements? Happy to discuss further!

**Comment by arupke** [comment]
Sorry if I'm jumping in on something y'all have already hashed out. Yeah, I think you're right about simplifying. Just wondering if, for instance, we should make national parks, monuments, etc. purple to be more consistent with what they're doing? Or military res pink? But if you changed those for specific reasons, forge ahead! We don't need to get to far down in the weeds on this...

**Comment by jjhi11** [comment]
There is an Owner Agency field that simplifies it pretty well. Check out the values there. Could I use these values? Obviously different colors though.
![owneragency](https://user-images.githubusercontent.com/27784116/91869454-2404c100-ec33-11ea-8495-8a9a087614e3.PNG)

**Comment by arupke** [comment]
The values seem reasonable to me. However, I would go with a color scheme closer to what we have been discussing.

**Comment by marthajensen** [comment]
@jjhi11 I've added the updated mining districts to a new mineral_metals Service. I didn't overwrite our other service because I removed the old Admin Ownership layer, thus changing the Layer ID for the BLM WSA Mineral Land Assessment. The new service is at https://utahdnr.maps.arcgis.com/home/item.html?id=83bb5b0bafb04049b5b92ce4a4ed8204  The mining districts have a new symbology, based on the TYPE field. When you have switched all the layers over to the new service, let me know. I'll delete the old service then

**Comment by jjhi11** [comment]
@marthajensen Done. All migrated to the new service in the code

**Comment by marthajensen** [comment]
@jjhi11 Thanks! I'm going to delete the old service now

**Comment by arupke** [comment]
@marshallrobinson , @marthajensen , @jjhi11 , @StephMills , So, I think we could charge some time to UBL1 for these updates. I would probably be somewhat conservative in charging these activities though... It's a bit gray for me whether it fits under the grant.

**Comment by StephMills** [comment]
Mining Districts time can go to UGP2, I specified updating the mining districts and webmaps in that scope of work. I think the land ownership work is probably ok under UBL1, but anything else would be unfunded.
