### ISSUE TITLE
More WSA MLAs to add

### ISSUE THREAD

**Issue by arupke** [UGS-GIO/Minerals-Metals#12]
We have more WSA MLAs to add to the map that were scanned during this fiscal year.

The geodatabase (MLA_data.gdb) with the MLA locations is at:
M:\Shared drives\UGS_Shared\Rupke\BLM_MLA

The WSA MLA scanned files are in the same folder under the MLAs folder.

Time spent on this can be charged to UBL1.

Let me know if you have any questions!

**Comment by arupke** [comment]
This automatically assigned Martha... Don't know if that's right or not?

**Comment by marthajensen** [comment]
ya - the assignment is right - I'll have a look at the data and let you know if I have questions :)

**Comment by arupke** [comment]
Thanks, Martha!

**Comment by marthajensen** [comment]
@arupke the WSA PDF's have been added to the app.
