### ISSUE TITLE
Add Industrial Mineral Layers

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/Minerals-Metals#13]
FY22 Grant funded (2 project funding codes)

-Contact Andrew Rupke for more information abt this in FY22

**Comment by CyndiAndersen** [comment]
@marthajensen, I finished the review of this FGDB.  
[IM_layer_updates.gdb.zip](https://github.com/UGS-GIO/Minerals-Metals/files/8044282/IM_layer_updates.gdb.zip)
There are 4 feature classes in the gdb.   3 of which are new: alunite, phosphate, and potash.
The silica feature class needs to replace the existing layer in Minerals web map.
Also, this information is downloadable on their web map.

**Comment by arupke** [comment]
@CyndiAndersen , Thanks!

@marthajensen , 
The work on these IM layers can be charged to UGP3. 
A couple questions... there is some text that will be attached to these layers. Should I go ahead and have Mike V. and Stephanie C. review that?

Let me know if you have any questions... Thanks!

**Comment by marthajensen** [comment]
@arupke 

Yes, send the attached text through the normal review process. Thanks!

**Comment by marthajensen** [comment]
@arupke This may be easier to talk about in person but I'm going to try to explain the differences and ask a few questions. If it's easier, lets schedule a Google Meet to go over this. 

 Within each published IM feature class, we have a standard set of fields: 'UnitSymbol', 'UnitName', 'Age', 'geolref', 'res_pot_rank'. I also always add a field named 'Commodity' (just an FYI - adding this field is not something you need to worry about). The 'Commodity' field is equal to the name of the IM (example 'Commodity'= Silica for the whole field). 

Within the popup on the web app, we show 'Age' and 'Unit Name' (shown below) so these fields are important that they exist in each feature class. 

![image](https://user-images.githubusercontent.com/11522897/155220924-99668e37-0f04-4abe-bdd0-6bb8882279e4.png)




Here's my review/questions:

**Alunite** - This is a new point layer and all the other IM layers are polygons. I will symbolize the points so they look the same as the polygon layers (red = high, orange = moderate, blue = undetermined). 

- _Missing fields_ (based on already published IM layers): 'UnitSymbol', 'UnitName', 'Age' and 'geolref'. 
- _Proposed changes_: The symbolization field ('res_pot_rank') is called 'res_pot_ranking' in the Alunite feature class. I will rename that field to 'res_pot_rank' to match the other layers. 
- __Questions/Observations_: 1. The Alunite feature class has a field named 'Reference'. Can I rename that field to 'geolref' to match the 'geolref' field in the other IM feature classes? 
2. Do we need to add the 'UnitName' and 'Age' field to satisfy the web popup or is this feature class meant to have a different type of popup than the other IM layers? 
3.  I'm not sure the 'UnitSymbol' field is shown anywhere in the app, so we probably don't need to add that one. 

**Phosphate** - looks good, no questions 

**Potash** -
- _Missing fields_ (based on already published IM layers): 'UnitSymbol', 'UnitName', 'Age'
- _Proposed changes_: The symbolization field ('res_pot_rank') is called 'res_pot_ranking' in the Potash feature class. I will rename that field to 'res_pot_rank' to match the other layers. 
- _Questions/Observations_: 1. The Potash feature class has a field named 'Reference'. Can I rename that field to 'geolref' to match the 'geolref' field in the other IM feature classes? 
2. Do we need to add the 'UnitName' and 'Age' field to satisfy the web popup or is this feature class meant to have a different type of popup than the other IM layers? This feature class does have a field named 'Name'. Is the 'Name' field in this feature class the same as 'UnitName' in the other IM feature classes?
3. I'm not sure the 'UnitSymbol' field is shown anywhere in the app, so we probably don't need to add that one. 


**Silica** - looks good, no questions


Last question -- in the popup, we link to a "Layer Information" writeup about the GIS data. Is that the text that is going through review right now?

**Comment by arupke** [comment]
@marthajensen , Hi, Martha... I'm at a conference for the first part of this week. I'll hopefully be able to get back to you on this towards the end of this week or the beginning of next. It probably would be easiest to have a discussion... I'll check in soon.

@marshallrobinson , Hi, Marshall... for this particular task... adding these IM layers, I'm shooting for within the next couple of months...

**Comment by arupke** [comment]
@marthajensen , Hi, Martha... I'm at a conference for the first part of this week. I'll hopefully be able to get back to you on this towards the end of this week or the beginning of next. It probably would be easiest to have a discussion... I'll check in soon.

@marshallrobinson , Hi, Marshall... for this particular task... adding these IM layers, I'm shooting for within the next couple of months...

**Comment by marthajensen** [comment]
@arupke has the text that will be attached to the layers been through review? If so, where would I find it?

**Comment by marthajensen** [comment]
I chatted with @arupke 

The reviewed text for the layers is at G:\Shared drives\UGS_Shared\Rupke\IM_layers

He said "the potash text can be used for both potash and alunite."

@jjhi11 I've got the data complete for this issue, I will look it over one more time and comment here when it's been published

**Comment by marthajensen** [comment]
@jjhi11 Three new layers need to be added to the Industrial Mineral Group in the web application. One is a point layer and the other three are polygon layers

**Alunite** - new Point layer (we don't have any other IM point layers) (Layer ID 15) - Symbolized the same as all of the IM polygon layers - the orange point is Moderate and the blue point is Undetermined. There are no High value points (which are typically red in the polygon layers.
Alunite Layer Information for web popup (uses the same Layer Information at Potash):"\\ugspub.nr.utah.gov\Sites\WWWROOT\UGSPub\publications\blm_mineral_resources\Alunite.pdf"

**Phosphate** - polygon IM layer just like all the rest of the IMs (Layer ID 17)
Phosphate Layer Information for web popup: "\\ugspub.nr.utah.gov\Sites\WWWROOT\UGSPub\publications\blm_mineral_resources\Phosphate.pdf"

**Potash** - polygon IM layer just like all the rest of the IMs (Layer ID 13)
Potash Layer Information for web popup: "\\ugspub.nr.utah.gov\Sites\WWWROOT\UGSPub\publications\blm_mineral_resources\Potash.pdf"

**Silica** - replacement layer for old Silica layer - no recoding should be required. I overwrote the old Layer 


Popup layer information for all web layers (rows 8,9): https://docs.google.com/spreadsheets/d/1aYDaH9TQ3r7e_d46qhRwcOL0ljJx8xdtRN1vr7vqZfg/edit#gid=0

URL: https://services.arcgis.com/ZzrwjTRez6FJiOq4/arcgis/rest/services/Metal_Mineral_Resources_web_View/FeatureServer

**Comment by marshallrobinson** [comment]
#17
