### ISSUE TITLE
Limestone layer is displaying the gypsum layer

### ISSUE THREAD

**Issue by arupke** [UGS-GIO/Minerals-Metals#14]
Under the "Industrial Mineral Resource Potential" layers... When I click to display the limestone layer, it's showing the gypsum layer.

**Comment by marthajensen** [comment]
Fixed - @arupke please check and make sure it looks good to you

**Comment by arupke** [comment]
Looks good. Thanks, Martha! @marthajensen

**Comment by marthajensen** [comment]
:)
