### ISSUE TITLE
This Application Needs New Data to Replace Existing Layer

### ISSUE THREAD

**Issue by arupke** [UGS-GIO/Minerals-Metals#19]
### Name of Existing Layer (as it appears in the application)

Critical Minerals

### Folder path of data

M:\Shared drives\UGS_Shared\Rupke\CM GIS

### Why do you feel this application needs what you're requesting?

We need to replace the existing Critical Mineral layer with an updated layer that accompanies our new CM publication. The updated geodatabase is in the specified location. We should remove the older CM GIS data, but keep it available for download in the "about" tab. However, we should also have the new data available for download. We should also link to the new publication in the about tab (https://ugspub.nr.utah.gov/publications/circular/c-135.pdf) and the new critical mineral list (https://www.federalregister.gov/documents/2022/02/24/2022-04027/2022-final-list-of-critical-minerals). I'm happy to discuss. Thank you!

### Who has reviewed your database so far (e.g. Schema, Field Types, Topology, etc.)?

none.

### Who has reviewed your science and grammar so far?

Mike VB., Stephanie C.

**Comment by arupke** [comment]
@nmpayne , Hi, Nate. Yeah, it's a bit pared down for this version.
For points, we can just display: commodity, label, and site name
For polys that are mining districts we can display: label, commodity, and district name
For other polys (i.e., "lithium potential in brine" or "magnesium dolomite outcrop"), i don't think we need any popups, in the legend they can just display as, "lithium potential in brine" or "dolomite outcrop."
Let me know what other questions you might have. Thank you!

**Comment by marshallrobinson** [comment]
@StephMills @arupke 

Hi folks! I received some critical mineral data from Stephanie yesterday. Is that data in addition to what Andrew has shared with us? Is there overlap?

Thanks.

**Comment by StephMills** [comment]
Yes, that should be the same task. Sorry for the duplication, I had forgotten I gave the data to Andrew and he was handling this one. He and I have already talked about this so he can be the point of contact.

**Comment by arupke** [comment]
Hi, Jay. @jjhi11 

Thanks for your help on this! Below are my comments.... Happy to discuss if something doesn't make sense.

-Let's just use the lithium brine layer (remove the magnesium brine layer) and label it as "Magnesium and Lithium potential in brine"
-Let's remove the dolomite outcrop layer altogether--it just makes things too busy and is not terribly important (however, let's leave it in the database for download)
-In the critical mineral occurrences legend, let's remove any reference to "active producer, established resource, potential resource, other deposit"; we didn't attribute the GIS according to that this time around
-The critical mineral occurrences should be mapped on top of the critical mineral areas
-This is the hard part... I'm happy to discuss this if you think of a better way to do this. Can we make the critical mineral areas that correspond with a given commodity in occurrences the same color as those occurrences? Then we can remove those from the legend (so remove 'notable past production,' 'occurrence,' 'other known mineralization,' 'past production,' and 'past production or known mineralization' from the legend). However, those areas should still be "clickable" as you have them. Does that make sense?

Thanks!

**Comment by marshallrobinson** [comment]
@jjhi11 

Looks great overall, well done. Below are a few comments/suggestions:

**Review comments**
- [ ] In About Panel: Instead of "new GIS data" and "old GIS data", I suggest putting "current GIS data", and "<year> GIS data" (assuming there's a year associated with the old data). 
- [ ] When clicking on an "Other Critical Mineral Areas" polygon that overlaps a "Lithium and Mag..." polygon, the popup shows that there is a second popup to scroll (e.g. "1 of 2"), but it just closes the popup. Is it possible to hide the "1 of 2"?
- [ ] The Land Ownership layer is broken (on LIVE and test application). Can it get fixed for the new release? Can we use this layer instead?

**Comment by jjhi11** [comment]
@marshallrobinson Can't really find a quick solution for the second comment. I have the others finished. Check it

**Comment by marshallrobinson** [comment]
Looks good, thanks
